### ISSUE TITLE
CI/CD Report which test failed

### ISSUE THREAD

**Issue by AssemblyJohn** [EVerest/libevse-security#45]
At the moment there is no detailed report on which test from within a testcase file has failed. Logs would be required to identify the specific test.

**Comment by andistorm** [comment]
An example can be found here: https://github.com/EVerest/libevse-security/actions/runs/7887550157/job/21523045379

Probably the reason for this issue is the structure of this script: https://github.com/EVerest/libevse-security/blob/main/.ci/build-kit/install_and_test.sh

If it fails in [executing the tests](https://github.com/EVerest/libevse-security/blob/main/.ci/build-kit/install_and_test.sh#L15) it doesn't [run the `cp` command](https://github.com/EVerest/libevse-security/blob/main/.ci/build-kit/install_and_test.sh#L17)

I will have look on it.

**Comment by AssemblyJohn** [comment]
Understood, it would be best to exec the CP regardless.

**Comment by AssemblyJohn** [comment]
Closed with: https://github.com/EVerest/libevse-security/pull/69
